# Site settings
title:       Vlad Samoylov
email:       samoylov.dev@gmail.com
author:      Vlad Samoylov
description: "Frontend developer Vlad Samoylov's blog"
baseurl:     ""
url:         "https://vladsamoylov.ru"
date_format: "%-d %b, %Y"
date_format_short: "%-d %b"

# Google services
google_verification: Ms6urkVt3RUsYExuXIpYIuGYT-iu890cmiz-WFoSNr4
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-46523265-2
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: true
fb_page_id: 1668450876797501



# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: somevlad
bitbucket_username:
stackoverflow_id:
twitter_username: somevlad
skype_username: some_vlad
steam_nickname:
google_plus_id:
linkedin_username: vladislav-samoylov-136606b9
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
telegram_username: some_vlad
vk_id:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me! I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  style: compressed
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor, markdown-cheatsheet.md]
